### PR TITLE
Fix for issue 503

### PR DESCRIPTION
**Pull request by q2apro**
https://github.com/q2a/question2answer/issues/503

### CODE REVIEW

**Comment by svivian** [comment]
Would you be able to make a PR against the 1.8 branch instead? There are some coding style changes on the 1.8 branch that would conflict with this.

**Comment by svivian** [comment]
Hi @q2apro are you able to redo this PR against the 1.8 branch? If you don't have time that's fine, I can do it myself later.

**Comment by q2apro** [comment]
Sorry, really no time at the moment.

**Comment by svivian** [comment]
Fixed by #522

**Pull request closed without merging**
