### PR TITLE
Simplify hidden HTML and avoid its detection as malware

### PR DESCRIPTION
**Pull request by pupi1985**
Seems to be working based on this comment: http://www.question2answer.org/qa/62349/malware-detected-in-q2a-code?show=62404#c62404

### CODE REVIEW

**Comment by ProThoughts** [comment]
cool! thanks for the quick fix.

**Comment by svivian** [comment]
We use absolute positioning so that the image is pre-loaded and appears instantly when doing an action (to show something is happening). Unfortunately browsers don't load images inside `display:none`, so on a slow connection it can take a second for the icon to display, which defeats the purpose.

`visibility:hidden` does load the image but it takes up space on the page. We can add `position:absolute; top:0` but we may be back to square one with that.

I don't think pre-loading via JS is feasible either as the image URL is part of the CSS (different themes have different loading icons).

**Comment by pupi1985** [comment]
I can confirm the browser caching issue. I amended the commit. The solution is overkill on purpose: to avoid any theme CSS change to incidentally make the hidden element visible.

**Comment by svivian** [comment]
OK thanks, hopefully this stops the bogus malware alert.

**Comment by ProThoughts** [comment]
This is working, no malware alert now. I added this patch on below site.
https://sitecheck.sucuri.net/results/meta.question2answer.info

**Comment by ProThoughts** [comment]
@svivian , I feel you should release q2a v1.8.1 because of this patch. thanks!

**Pull request merged**
