### PR TITLE
Prevent directory listings

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by svivian** [comment]
You already provided this in #342 :)

**Comment by DanielRuf** [comment]
This is for the 1.8 branch, or you you merge the current dev with the 1.8 branch?

Because the 1.8 is many commits before the current dev branch.

**Comment by svivian** [comment]
Yes they will be merged at some point. Basically it works like this:

- `master` is the current stable branch (1.7.2 currently).
- `dev` is branched off `master` for bug fixes to the 1.7 line. It's merged into master for a patch release (1.7.2, 1.7.3 etc).
- `1.8` is branched off `dev` for the next version of Q2A with new features.
- The bug fixes from `dev` are merged into `1.8` as we go along (usually on each patch release).

**Comment by DanielRuf** [comment]
Ah ok, thanks for letting me know, did not know how this is handled and dev is used as upstream for 1.8 and will be merged.

**Pull request closed without merging**
