### PR TITLE
captcha language option

### PR DESCRIPTION
**Pull request by q2apro**
added language option for captcha, for internationalization

### CODE REVIEW

**Comment by svivian** [comment]
Is there a need for this? reCAPTCHA should default to the language of the visitor automatically.

**Comment by q2apro** [comment]
No, it does not default. Otherwise I had not implemented it...

**Comment by svivian** [comment]
According to [this](https://developers.google.com/recaptcha/docs/display#config) it does. I tested and it's working for me (browser language set to French):

captcha lang

Maybe you don't have the browser language set?

**Comment by q2apro** [comment]
I am always using an English browser but surfing German, French and Lithuanian websites. 

The browser language is not a guarantee that the user / website uses this language as well. Again one of those big fails in usability.

**Comment by svivian** [comment]
Yes I suppose that users may have their browser set up incorrectly. Plus if a site is in German it's fair to assume any visitors registering/posting should be able to read German. Will test & merge when I get time.

**Comment by DanielRuf** [comment]
Thought about this. Why not define a sitewide language (too) which is added to the whole site using `<html lang="...">`?

**Comment by svivian** [comment]
We already have a site language option, so I've added this to the reCAPTCHA plugin instead of using a separate option, and also added it to the `<html>` tag. Thanks for bringing up the issue.

**Comment by q2apro** [comment]
... as long as the language codes fit: https://developers.google.com/recaptcha/docs/language

**Comment by svivian** [comment]
Yes they are all standard language codes. If the site is using a language that reCAPTCHA does not support, it will fall back to the user's browser setting again.

**Pull request closed without merging**
