### PR TITLE
Improved Forgot Password Procedure

### PR DESCRIPTION
**Pull request by q2apro**
_Preamble: Did not know how I can prevent the other two commits from 2015..._

**NEW:**
1. Forgot password, enter username or email
2. Mail goes to user, front end shows: check your email
3. User clicks link in email, comes to reset page, data (code and email/handle) gets submitted by JS automatically
4. User gets the 2nd email that contains his new password, frontend shows: "password was sent to you", and the input fields, cursor in password field blinking
5. User checks his email, copies the password, done. 

Not perfect, but better than before!

### CODE REVIEW

**Comment by q2apro** [comment]
That is the new code: https://github.com/q2a/question2answer/pull/455/commits/b53a844520bb64fce9c18b935871ac0c978d7aed

**Comment by svivian** [comment]
Thanks for the effort. Not sure if I'm missing something, but does this only submit the form with JS? The process is exactly the same besides that? If so, while I see it's a small improvement it doesn't really solve the problem. The user still gets two emails and their password is still sent via email.

---

Also just a few notes on the code itself:

- For some reason this has been mixed up with other PRs/commits, maybe check the Github docs in case there's something you did wrong.

- The PR has been sent against the master branch, but for new features it should be against the 1.8 branch. See the [contributing guide](https://github.com/q2a/question2answer/blob/dev/CONTRIBUTING.md) for details.

- The coding style seems to be messed up. For example, [here](https://github.com/q2a/question2answer/pull/455/commits/b53a844520bb64fce9c18b935871ac0c978d7aed#diff-9c1f3a0c62fb0e9f3b09eb6937adc818L23) the curly brace is on the next line. Maybe this was done automatically by your text editor/IDE? If so, see if you can configure it to follow our style (see the contributing file) or turn off automatic formatting.

Hope that helps for future PRs :)

**Comment by q2apro** [comment]
I am very short on time recently and cannot spent extra hours to tidy up the details, esp. Github (I missed to sync beforehand). Sorry for that. 

And yes, the process is improved. We tested it already. 

You can leave it open until someone else finds it again and reports back. 

I started to use brackets on the new line. I am not sure, saw this at Gideon or someone else. 

Greetings.

**Comment by DanielRuf** [comment]
Very bad idea never send any passwords via email.

> 4. User gets the 2nd email that contains his new password, frontend shows: "password was sent to you", and the input fields, cursor in password field blinking

**Comment by svivian** [comment]
Solved by #457

**Pull request closed without merging**
