### PR TITLE
[BugFix] - restrict the user to post duplicate questions

### PR DESCRIPTION
**Pull request by amiyasahu**
do not allow user to post the duplicate question once more time . It
checks the last 5 questions and compares with the current one . If any
of them appears to be same the user will be warned and the question will
not be posted
Fixes - #309

### CODE REVIEW

**Comment by svivian** [comment]
Is there a reason for the new function? Shouldn't `qa_db_qs_selectspec` cover what we need? You can call it with mostly blanks and it should be as simple as your new function.

    qa_db_qs_selectspec(null, 'created', 0, null, null, false, false, 5);

**Comment by amiyasahu** [comment]
An small correction to your suggestion - full post is needed as we need the content of the post 

```
qa_db_qs_selectspec(null, 'created', 0, null, null, false, true, 5);
```
The result will remain same by the way you have provided . Initially I also thought this way . 
But with this , the code does an extra join with the user table which is not necessary . For that shake It costs me a extra function .

The existing code of `qa_db_qs_selectspec` will call the qa_db_posts_basic_selectspec like this - 
```
$selectspec=qa_db_posts_basic_selectspec($voteuserid, $full);  //$user variable becomes true by default
```
But the new function calls like this with false for the user variable 
```
$selectspec=qa_db_posts_basic_selectspec(null, true, false);  // false to the $user variable 
```

Which avoid the unnecessary join with the user table . If the tables were huge then it would make a significance difference ( what I believe ).

If we go for minimum code changes we can go with the existing function , but if we see the performance point of view it is worthy to add an extra function . 

What do you say ?

**Comment by svivian** [comment]
Actually that join inside `qa_db_qs_selectspec` speeds up the query. This is one of the things Gideon told me when I took over Q2A development that I didn't know about MySQL. Basically, joining the table to itself like that means we do a fast select based on the table index. See the [last point here](https://www.percona.com/blog/2009/09/12/3-ways-mysql-uses-indexes/) for more info.

So you can call `qa_db_qs_selectspec` with `$full` set to true as you said, and it will be efficient.

**Comment by amiyasahu** [comment]
Ok , Still I am not sure how can a extra join will improve the performance of the db query ( may be due to my limited knowledge ) .

I have created another PR #323 to avoid unnecessary commits with using the existing q2a functions . Both of them works in the same way 

I am closing this for now . Thank you :smile:

**Pull request closed without merging**
