### PR TITLE
New answer with Ajax inserted at the bottom

### PR DESCRIPTION
**Pull request by phy25**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Why bottom? It is just once and it makes sense to put it to the top (UX). insertBefore is right imho =)

**Comment by phy25** [comment]
When there are already some answers, answer form is at the bottom, not the top. Thus if you finished your answer, you don't need to scroll to the top to see your answer.
(Hopes I haven't modified my theme :joy:)

**Comment by DanielRuf** [comment]
But append adds it to the end of the selector. prepend(To) and insertBefore add it to the beginning.

**Comment by phy25** [comment]
I don't think there is any problem with the code. If the strategy is not suitable, feel free to discuss.

**Comment by DanielRuf** [comment]
Mh, your solution could make more sense as StackOverflow does it this way. The form and new answers are at the bottom. The later is already the case in question2answer but the form is still on the top, you are right. Would improve the UX and be more consistent.

**Comment by svivian** [comment]
Sorry I meant to comment on this earlier. It looks like from the code that only the answer is added at the bottom but the answer form is still opened at the top?

I think that the submitted answer should be placed at the same point it's being written, but that could be the bottom. (On my site I actually do this using a theme override.)

In other words, we should add an option for the answer form location (Top/Bottom) then the answer stays at that location when submitted.

**Comment by DanielRuf** [comment]
> bottom but the answer form is still opened at the top?

Right.

> In other words, we should add an option for the answer form location (Top/Bottom) then the answer stays at that location when submitted.

Great idea. This is also what I head in my head, form and answer at the same location which improves UX and usability and reflects how this is on SO and other platforms =)

**Comment by phy25** [comment]
I see. So the Javascript code should detect the position of the form and insert the new answer into the proper position.

I will modify the pull request later this week.

**Comment by svivian** [comment]
I *think* you don't need to modify the Javascript at all, just move the answer form location to be after the answers. When the answer is added it replaces the form with the answer content.

**Pull request closed without merging**
